const ActionTypes = {
    ADD_CART: 'ADD_CART',
    REMOVE_CART:'REMOVE_CART',
    INCREMENT_ITEM: 'INCREMENT_ITEM',
    DECREMENT_ITEM: 'DECREMENT_ITEM',
    LOAD_PRODUCTS: 'LOAD_PRODUCTS',
    FAIL_PRODUCTS: 'FAIL_PRODUCTS',
    SUCCESS_ADD: 'SUCCESS_ADD',
}

export default ActionTypes