const ActionTypes = {
    ADD_CART: 'ADD_CART',
    REMOVE_CART:'REMOVE_CART',
    INCREMENT_PRODUCT: 'INCREMENT_PRODUCT',
    DECREMENT_PRODUCT: 'DECREMENT_PRODUCT',
    LOAD_PRODUCTS: 'LOAD_PRODUCTS',
    FAIL_PRODUCTS: 'FAIL_PRODUCTS'
}

export default ActionTypes